spring:
  application:
    name: cinema-management

  datasource:
    url: jdbc:h2:mem:cinema_db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password: ""

  jpa:
    hibernate:
      ddl-auto: update

  h2:
    console:
      enabled: true
      path: /h2-console

# ================= JWT =================
jwt:
  secret: celso-portioli-11-setembro-123456
  expiration: 3600000 # 1h
